/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AcmeAbout {
    }
    interface AcmeBanner {
        /**
          * Text written inside the button
         */
        "callToAction": string;
        /**
          * Title for the banner
         */
        "titleBanner": string;
    }
    interface AcmeFooter {
        /**
          * Footer main text
         */
        "footerText": string;
    }
    interface AcmeMenu {
    }
    interface AcmeSubBanner {
        /**
          * An hightlighted word for the title of the under-banner section
         */
        "boldWord": string;
        /**
          * A title for the under-banner section
         */
        "subTitle": string;
    }
    interface FormFinanziabilita {
    }
    interface NpmCentralBanner {
        /**
          * An hightlighted word for the title of the under-banner section
         */
        "boldWord": string;
        /**
          * A title for the under-banner section
         */
        "subTitle": string;
    }
}
declare global {
    interface HTMLAcmeAboutElement extends Components.AcmeAbout, HTMLStencilElement {
    }
    var HTMLAcmeAboutElement: {
        prototype: HTMLAcmeAboutElement;
        new (): HTMLAcmeAboutElement;
    };
    interface HTMLAcmeBannerElement extends Components.AcmeBanner, HTMLStencilElement {
    }
    var HTMLAcmeBannerElement: {
        prototype: HTMLAcmeBannerElement;
        new (): HTMLAcmeBannerElement;
    };
    interface HTMLAcmeFooterElement extends Components.AcmeFooter, HTMLStencilElement {
    }
    var HTMLAcmeFooterElement: {
        prototype: HTMLAcmeFooterElement;
        new (): HTMLAcmeFooterElement;
    };
    interface HTMLAcmeMenuElement extends Components.AcmeMenu, HTMLStencilElement {
    }
    var HTMLAcmeMenuElement: {
        prototype: HTMLAcmeMenuElement;
        new (): HTMLAcmeMenuElement;
    };
    interface HTMLAcmeSubBannerElement extends Components.AcmeSubBanner, HTMLStencilElement {
    }
    var HTMLAcmeSubBannerElement: {
        prototype: HTMLAcmeSubBannerElement;
        new (): HTMLAcmeSubBannerElement;
    };
    interface HTMLFormFinanziabilitaElement extends Components.FormFinanziabilita, HTMLStencilElement {
    }
    var HTMLFormFinanziabilitaElement: {
        prototype: HTMLFormFinanziabilitaElement;
        new (): HTMLFormFinanziabilitaElement;
    };
    interface HTMLNpmCentralBannerElement extends Components.NpmCentralBanner, HTMLStencilElement {
    }
    var HTMLNpmCentralBannerElement: {
        prototype: HTMLNpmCentralBannerElement;
        new (): HTMLNpmCentralBannerElement;
    };
    interface HTMLElementTagNameMap {
        "acme-about": HTMLAcmeAboutElement;
        "acme-banner": HTMLAcmeBannerElement;
        "acme-footer": HTMLAcmeFooterElement;
        "acme-menu": HTMLAcmeMenuElement;
        "acme-sub-banner": HTMLAcmeSubBannerElement;
        "form-finanziabilita": HTMLFormFinanziabilitaElement;
        "npm-central-banner": HTMLNpmCentralBannerElement;
    }
}
declare namespace LocalJSX {
    interface AcmeAbout {
    }
    interface AcmeBanner {
        /**
          * Text written inside the button
         */
        "callToAction"?: string;
        /**
          * Title for the banner
         */
        "titleBanner"?: string;
    }
    interface AcmeFooter {
        /**
          * Footer main text
         */
        "footerText"?: string;
    }
    interface AcmeMenu {
    }
    interface AcmeSubBanner {
        /**
          * An hightlighted word for the title of the under-banner section
         */
        "boldWord"?: string;
        /**
          * A title for the under-banner section
         */
        "subTitle"?: string;
    }
    interface FormFinanziabilita {
    }
    interface NpmCentralBanner {
        /**
          * An hightlighted word for the title of the under-banner section
         */
        "boldWord"?: string;
        /**
          * A title for the under-banner section
         */
        "subTitle"?: string;
    }
    interface IntrinsicElements {
        "acme-about": AcmeAbout;
        "acme-banner": AcmeBanner;
        "acme-footer": AcmeFooter;
        "acme-menu": AcmeMenu;
        "acme-sub-banner": AcmeSubBanner;
        "form-finanziabilita": FormFinanziabilita;
        "npm-central-banner": NpmCentralBanner;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "acme-about": LocalJSX.AcmeAbout & JSXBase.HTMLAttributes<HTMLAcmeAboutElement>;
            "acme-banner": LocalJSX.AcmeBanner & JSXBase.HTMLAttributes<HTMLAcmeBannerElement>;
            "acme-footer": LocalJSX.AcmeFooter & JSXBase.HTMLAttributes<HTMLAcmeFooterElement>;
            "acme-menu": LocalJSX.AcmeMenu & JSXBase.HTMLAttributes<HTMLAcmeMenuElement>;
            "acme-sub-banner": LocalJSX.AcmeSubBanner & JSXBase.HTMLAttributes<HTMLAcmeSubBannerElement>;
            "form-finanziabilita": LocalJSX.FormFinanziabilita & JSXBase.HTMLAttributes<HTMLFormFinanziabilitaElement>;
            "npm-central-banner": LocalJSX.NpmCentralBanner & JSXBase.HTMLAttributes<HTMLNpmCentralBannerElement>;
        }
    }
}
