/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AcmeBanner {
        /**
          * Text written inside the button
         */
        "callToAction": string;
        /**
          * Title for the banner
         */
        "titleBanner": string;
    }
    interface AcmeSubBanner {
        /**
          * An hightlighted word for the title of the under-banner section
         */
        "boldWord": string;
        /**
          * A title for the under-banner section
         */
        "subTitle": string;
    }
}
declare global {
    interface HTMLAcmeBannerElement extends Components.AcmeBanner, HTMLStencilElement {
    }
    var HTMLAcmeBannerElement: {
        prototype: HTMLAcmeBannerElement;
        new (): HTMLAcmeBannerElement;
    };
    interface HTMLAcmeSubBannerElement extends Components.AcmeSubBanner, HTMLStencilElement {
    }
    var HTMLAcmeSubBannerElement: {
        prototype: HTMLAcmeSubBannerElement;
        new (): HTMLAcmeSubBannerElement;
    };
    interface HTMLElementTagNameMap {
        "acme-banner": HTMLAcmeBannerElement;
        "acme-sub-banner": HTMLAcmeSubBannerElement;
    }
}
declare namespace LocalJSX {
    interface AcmeBanner {
        /**
          * Text written inside the button
         */
        "callToAction"?: string;
        /**
          * Title for the banner
         */
        "titleBanner"?: string;
    }
    interface AcmeSubBanner {
        /**
          * An hightlighted word for the title of the under-banner section
         */
        "boldWord"?: string;
        /**
          * A title for the under-banner section
         */
        "subTitle"?: string;
    }
    interface IntrinsicElements {
        "acme-banner": AcmeBanner;
        "acme-sub-banner": AcmeSubBanner;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "acme-banner": LocalJSX.AcmeBanner & JSXBase.HTMLAttributes<HTMLAcmeBannerElement>;
            "acme-sub-banner": LocalJSX.AcmeSubBanner & JSXBase.HTMLAttributes<HTMLAcmeSubBannerElement>;
        }
    }
}
